server:
  port: 8000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: iam-service-route
              uri: http://iam-service:8001
              predicates:
                - Path=/api/v1/authentication/**,/api/v1/roles/**

            - id: follow-up-service-route
              uri: http://follow-up-service:8002
              predicates:
                - Path=/api/v1/**,/api/v1/notification/**
              filters:
                - JwtValidation

iam:
  service:
    url: http://iam-service:8001