server:
    port: 8000

spring:
    cloud:
        gateway:
            routes:
                ## http://localhost:4004/auth/login
                ## API-GATEWAY -> http://auth-service:4005/login
                - id: iam-service-route
                  uri: http://iam-service:8001
                  predicates:
                      - Path=/api/v1/authentication/**,/api/v1/roles/**

                - id: follow-up-service-route
                  uri: http://follow-up-service:8002
                  predicates:
                      - Path=/api/v1/**,/api/v1/follow-up/**
                  filters:
                    - JwtValidation
