spring.application.name=profiles-service

server.port=8007

spring.datasource.url=jdbc:postgresql://profiles-service-db:5432/profiles_database
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.naming.physical-strategy=org.lorem.shared.domain.model.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy