version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://profiles-service-db:5432/profiles_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8004:8004"
    depends_on:
      - profiles-service-db

  profiles-service-db:
    image: postgres:15
    environment:
      POSTGRES_DB: profiles_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"