spring.application.name=legal-case-service

server.port=8006

spring.datasource.url=jdbc:postgresql://legal-case-service-db:5432/legal_case_database
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=legalcase-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer