spring.application.name=feeing-service

server.port=8004

spring.jpa.hibernate.naming.physical-strategy=org.lorem.feeingservice.shared.domain.model.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy