spring.application.name=iam-service

server.port=8005

spring.datasource.url=jdbc:postgresql://iam-service-db:5432/iam_database
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0


spring.jpa.hibernate.naming.physical-strategy=org.lorem.shared.domain.model.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy